### ISSUE TITLE
Won't import from archive if no forename

### ISSUE THREAD

**Issue by j162011** [sdenier/Geco#40]
When I download an archive of runners from the UK SportIdent website, some of the runners do not have a forename in the CSV file. GecO stops importing runners into the archive at this point. 

It also stops importing runners if they haven't provided a national membership number. 

Would it be possible to allow import of runners with some missing information?

![image1](https://cloud.githubusercontent.com/assets/9338003/6108986/95468fe8-b06f-11e4-821c-d8c562a2085d.jpg)

**Comment by sdenier** [comment]
Can you drop the CSV file in this issue? It would help me to track down other issues

**Comment by j162011** [comment]
https://cuoc.soc.srcf.net/docs/2015_SI_Archive.csv

**Comment by sdenier** [comment]
There is one main issue: the archive manager was designed to hold a database of runner with a national membership, so it **expects an archive id**. I can make it more robust to accept some empty fields but not the archive id. By running your file, I got only 4900 entries while the file contains 25000 lines.

Where does this base comes from?

Other issues from your file:
- there is no category defined (the 'Short' column), so all runners are imported with a no-name category
- there is an issue with a line containing an html-encoded entity \&#263; (Spudi&#263;). Problem is the supplementary semi-colon at end - it shifts all fields to the right and triggers an error

     ;"713713";"Spudi\&#263;";"Valeria";"97";"f";"60";;"IND";;;;;;;;"";"";"";;;;;;;;;;"0"

**Comment by j162011** [comment]
I downloaded the file from the SportIdent UK website. There were several different options (OE2003, OE2010) and I chose the OE2003 format as I thought that would probably be what was supported by GecO. 

(I can supply a login and password by email if you would like to have a look on the SI website yourself)

The category can be exported into Text1 2 or 3 depending on the option I choose on the SportIdent website. From what I read (http://www.fabian4.co.uk/support/ImportExport.aspx Section 5) the age class (e.g. M21) should go into text2. At the largest races there may be several sub classes of M21 (e.g M21E, M21L, M21S) which should go into the 'short' column?

**Comment by sdenier** [comment]
Yes, password/login would be useful (my gmail starts with simon.denier)

OE2003 is ok.

I need to think about it, but probably I will just set a random archive id for people with a missing id.

For the category, it is just an alternate way to filter competitors and rank them. So the age class is enough, or you can go for sub classes if you want to have a finer grain. Or you could just tell men and women apart if you want...

**Comment by sdenier** [comment]
The archive can now handle missing fields (names...) as well as missing archive id (will default to an auto-increment id above 999000000). To be released in 2.3.1

There is still an issue with some name using html-encoded entities in the BOF archive, but dealing with them would be costly - and there are only **four** of them right now.
For example : Spudi&#263; -> translated to Spudic by hand
