### ISSUE TITLE
Support for translation

### ISSUE THREAD

**Issue by davidpustai** [sdenier/Geco#46]
**Any intention to add translations to other languages?**

Our trainer likes Geco but doesn't understand English. We'd like to make it easier to use for her. I'm pretty sure others within the community would appriciate it and maybe even help develop the translations.

**Comment by sdenier** [comment]
It's pretty easy to provide custom translation files for Geco, although a bit cumbersome given the number of messages.

You should make a copy and edit these two files by appending the suffix of your current local.
https://github.com/sdenier/Geco/blob/master/src/net/geco/messages.properties
https://github.com/sdenier/Geco/blob/master/src/net/geco/ui/messages.properties

For example, if your locale is `de` (german), then you should rename your translated files to `messages_de.properties`. Geco will automatically pick up files for your current locale.

**Comment by davidpustai** [comment]
Thanks, if I come to do it, I'll make a pull request.
